#!/bin/bash
#!/bin/bash
add-apt-repository -u ppa:lightningnetwork/ppa

declare -a DEPS=( 
                    "pkg-config"
                    "gcc"
                    "autoconf"
                    "libtool"
                    "libgmp-dev"
                    "automake"
                    "python3"
                    "python3-mako"
                    "net-tools"
                    "zlib1g-dev"
                    "libsodium-dev"
                    "build-essential"
                    "make"
                    "software-properties-common"
                    "curl"
                    "postgresql"
                    "wget"
                    "ca-certificates"
                    "openssl"
                    "jq"
                    "ncat"
                    "tcl"
                    "git"
                    "magic-wormhole"
                    "libssl-dev"
                    "libjemalloc-dev"
                    "gnutls-bin"
                    "tclcurl"
                    "acl"
                    "autoconf"
                    "libacl1-dev"
                    "libcap-dev"
                    "libudev-dev"
                    "libtool"
                    "dnsmasq-base"
                    "snapd"
                    "libgsl-dev"
                    "libgbtools-dev"
                    "gawk"
                    "lightningd"
                    "snapd"
                )

apt install -y ${DEPS[@]} 
apt update -y 
apt upgrade -y 
apt autoremove -y

snap install bitcoin-core
ln -s /snap/bitcoin-core/current/bin/bitcoin{d,-cli} /usr/local/bin/


git clone https://github.com/ElementsProject/lightning.git
cd lightning
sudo apt-get install -y valgrind python3-pip libpq-dev
pip3 install -r requirements.txt

./configure
make
make install

tarfile="redis-stable.tar.gz"
url="http://download.redis.io/redis-stable.tar.gz"
REDISPORT=6379
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli
PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${REDISPORT}.conf"

# 
# Redis
cd /
rm -rf $tarfile
wget $url
tar -xzf $tarfile
cp /redis-stable/redis.conf /etc/redis/${REDISPORT}.conf
mkdir -p /var/redis
mkdir -p /etc/redis
mkdir -p /var/redis/${REDISPORT}

cd /redis-stable
make distclean
make test
ln -s /redis-stable/src/redis-server /usr/local/bin/redis-server
ln -s /redis-stable/src/redis-cli /usr/local/bin/redis-cli
ln -s /redis-stable/utils/redis_init_script /etc/init.d/redis_${REDISPORT}

update-rc.d redis_${REDISPORT} defaults



