#!/bin/bash
cd $(dirname $0)
img_name="$(cat img-name)"


lxc launch images:debian/buster $img_name
lxc config set $img_name security.nesting true
lxc restart $img_name
lxc file push ./init-redis $img_name/
lxc exec $img_name -- /init-redis

