#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

export VERSION=${1:-"1.16.6"}
export GO_OOS=${2:-"linux-amd64"}

export GO_TAR="go$VERSION.$GO_OOS.tar.gz"
export GO_SRC="https://golang.org/dl/"
export GO_URL="$GO_SRC/$GO_TAR"
export PATH=$PATH:user/local/go/bin

wget $GO_URL
rm -rf /usr/local/go /bin/go
tar -C /usr/local -xzf $GO_TAR
ln -s /usr/local/go/bin/go /bin
rm -rf $GO_TAR

